//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zadatak_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblClinicDoctor
    {
        public int DoctorId { get; set; }
        public int UserId { get; set; }
        public string UniqueNumber { get; set; }
        public string BankAccountNumber { get; set; }
        public string Department { get; set; }
        public string Shift { get; set; }
        public bool ResponsibleForPatientAdmission { get; set; }
        public Nullable<int> SuperiorManager { get; set; }
    
        public virtual tblClinicManager tblClinicManager { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
