//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zadatak_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblClinicManager
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblClinicManager()
        {
            this.tblClinicDoctors = new HashSet<tblClinicDoctor>();
        }
    
        public int ManagerId { get; set; }
        public int UserId { get; set; }
        public int Floor { get; set; }
        public int MaximumNumberOfSupervisedDoctors { get; set; }
        public int MinimumNumberOfSupervisedRooms { get; set; }
        public int NumberOfOmissions { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblClinicDoctor> tblClinicDoctors { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
