//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zadatak_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwClinicDoctor
    {
        public int UserId { get; set; }
        public string NameAndSurname { get; set; }
        public string IdentityCardNumber { get; set; }
        public string Gender { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string Citizenship { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string BankAccountNumber { get; set; }
        public string Department { get; set; }
        public int DoctorId { get; set; }
        public bool ResponsibleForPatientAdmission { get; set; }
        public string Shift { get; set; }
        public Nullable<int> SuperiorManager { get; set; }
        public string UniqueNumber { get; set; }
    }
}
